# Generated by Django 5.2.6 on 2026-02-04 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('company_bio', models.TextField(blank=True)),
                ('company_address', models.CharField(blank=True, max_length=500)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_handle', models.URLField(blank=True, max_length=500)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('facebook_handle', models.CharField(blank=True, max_length=100)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('default_signatory_name', models.CharField(blank=True, max_length=255)),
                ('default_signatory_title', models.CharField(blank=True, max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=100, unique=True)),
                ('credential_id', models.CharField(max_length=100, unique=True)),
                ('recipient', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=500)),
                ('program', models.CharField(blank=True, max_length=255)),
                ('certificate_type', models.CharField(choices=[('Completion', 'Completion'), ('Competence', 'Competence'), ('Attendance', 'Attendance')], default='Completion', max_length=20)),
                ('phrase', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField()),
                ('delivery_mode', models.CharField(blank=True, choices=[('Online', 'Online'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], max_length=20, null=True)),
                ('competence_result', models.CharField(blank=True, max_length=100, null=True)),
                ('competence_expiry_date', models.DateField(blank=True, null=True)),
                ('signatory_name', models.CharField(max_length=255)),
                ('signatory_title', models.CharField(max_length=255)),
                ('issuer_name', models.CharField(max_length=255)),
                ('issuer_location', models.CharField(max_length=500)),
                ('verification_link', models.URLField(blank=True, max_length=500)),
                ('qr_code', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['certificate_no'], name='credentiala_certifi_c434ae_idx'), models.Index(fields=['credential_id'], name='credentiala_credent_1ad803_idx'), models.Index(fields=['issuer', 'status'], name='credentiala_issuer__1b03f8_idx')],
            },
        ),
    ]
