# Generated by Django 5.2.6 on 2026-02-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0003_remove_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Blended', 'Blended'), ('In-Person', 'In-Person')], max_length=20, null=True),
        ),
    ]
