# Generated by Django 5.2.6 on 2026-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0004_alter_certificate_delivery_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='hours_cpd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
