# Generated by Django 5.2.6 on 2026-02-18 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_no', models.CharField(max_length=100, unique=True)),
                ('credential_id', models.CharField(max_length=100, unique=True)),
                ('recipient', models.CharField(max_length=255)),
                ('program_line1', models.CharField(max_length=255)),
                ('program_line2', models.CharField(blank=True, max_length=255)),
                ('issuer_name', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('year', models.CharField(max_length=4)),
                ('badge_svg', models.TextField(blank=True)),
                ('verification_link', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='credentialapp.certificate')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issuer', 'status'], name='credentiala_issuer__52aa90_idx'), models.Index(fields=['credential_id'], name='credentiala_credent_eea72e_idx')],
            },
        ),
    ]
