# Generated by Django 6.0.3 on 2026-04-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0007_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_no',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='credential_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credential_id',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
