# Generated by Django 6.0.3 on 2026-04-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0009_userprofile_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
